
name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        SECRET_KEY: "dummy-secret-key-for-ci"
        DEBUG: "True"
        DB_NAME: "test_db"
        DB_USER: "test_user"
        DB_PASSWORD: "test_password"
        DB_HOST: "localhost"
        DB_PORT: "5432"
        GOOGLE_CLIENT_ID: "dummy"
        GOOGLE_CLIENT_SECRET: "dummy"
        GITHUB_CLIENT_ID: "dummy"
        GITHUB_CLIENT_SECRET: "dummy"
        STRIPE_PUBLISHABLE_KEY: "dummy"
        STRIPE_SECRET_KEY: "dummy"
      run: |
        chmod +x manage.py
        python manage.py test
